"""
Django settings for secure_ecommerce_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party security apps
    'axes',  # Brute force protection
    'django_filters',  # Filtering for ViewSets
    # Local apps
    'authentication',
    'products',
    'orders',
    'payments',
    'reviews',
    'monitoring',  # Health monitoring and AI agent
    # REST Framework
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    # CORS must be first to handle preflight requests
    "corsheaders.middleware.CorsMiddleware",
    # Security middleware (adds security headers)
    'django.middleware.security.SecurityMiddleware',
    # Session middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Common middleware (URL rewriting, etc.)
    'django.middleware.common.CommonMiddleware',
    # CSRF protection
    'django.middleware.csrf.CsrfViewMiddleware',
    # Authentication middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Axes middleware (must be after authentication)
    'axes.middleware.AxesMiddleware',
    # Custom security middleware (audit logging and security headers)
    'authentication.middleware.AuditLoggingMiddleware',
    'authentication.middleware.SecurityHeadersMiddleware',
    # Monitoring middleware (track performance metrics)
    'monitoring.middleware.MonitoringMiddleware',
    # Messages middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    # Clickjacking protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'secure_ecommerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'secure_ecommerce_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('DB_NAME'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': env.str('DB_HOST'),
        'PORT': env.str('DB_PORT'),
        'OPTIONS': {
            # Connection timeout in seconds which is the time to wait for a connection to be established.
            'connect_timeout': env.int('DB_CON_TIMEOUT'),
            # SSL mode which is the SSL mode to use for the connection.
            # SSL mode can be one of the following:
            # - 'disable': No SSL encryption.
            # - 'prefer': Prefer SSL encryption, but allow non-SSL connections.
            # - 'require': Require SSL encryption, and reject non-SSL connections.
            # - 'verify-ca': Verify the certificate against a trusted CA.
            # - 'verify-full': Verify the certificate against a trusted CA and the server's hostname.
            'sslmode': env.str('DB_SSLMODE'),
        },
        'CONN_MAX_AGE': env.int('DB_CON_MAX_AGE'),  # Connection max age in seconds which is the time to keep the connection alive.
    }
}

# ============================================================================
# AUTHENTICATION CONFIGURATION
# ============================================================================

AUTH_USER_MODEL = 'authentication.User'




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - files larger than this use temporary file storage
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - max size for request body
FILE_UPLOAD_PERMISSIONS = 0o644  # File permissions for uploaded files
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Directory permissions

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# DJANGO REST FRAMEWORK & JWT AUTHENTICATION
# ============================================================================
#
# API endpoints require JWT credentials by default. Public-facing views
# (registration, login, password reset) explicitly override this with
# `AllowAny` so they remain accessible without a token.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Pagination for list views
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Filtering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Throttling (rate limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users: 100 requests per hour
        'user': '1000/hour',  # Authenticated users: 1000 requests per hour
    },
    # Exception handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    # Date/time formatting
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}

# Align Simple JWT lifetimes with the security recommendations documented in
# `jwt_oauth_otp_configuration.txt`. Adjust via environment variables if an
# environment needs shorter or longer validity windows.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Brute-force safeguards used by the login serializer. Override these values
# in the environment to tune how many failed attempts are tolerated and how
# long an account remains locked after the threshold is exceeded.
AUTH_LOCKOUT_THRESHOLD = env.int('AUTH_LOCKOUT_THRESHOLD', default=5)
AUTH_LOCKOUT_MINUTES = env.int('AUTH_LOCKOUT_MINUTES', default=15)

# ============================================================================
# HTTPS/SSL SECURITY CONFIGURATION
# ============================================================================

# Force HTTPS in production
# Set to True when behind a proxy that handles SSL termination (e.g., nginx, load balancer)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Force all HTTP requests to redirect to HTTPS
# Set to True in production when SSL is properly configured
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)

# Ensure cookies are only sent over HTTPS
# Set to True in production
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)

# Ensure CSRF cookies are only sent over HTTPS
# Set to True in production
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)

# Prevent cookies from being accessed by JavaScript (XSS protection)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Set SameSite attribute for cookies to prevent CSRF attacks
# Options: 'Strict', 'Lax', 'None'
# 'Strict': Cookie is never sent in cross-site requests
# 'Lax': Cookie is sent in top-level navigation (default, good balance)
# 'None': Cookie is sent in all cross-site requests (requires Secure flag)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HTTP Strict Transport Security (HSTS)
# Forces browsers to only use HTTPS for a specified period
# Set to True in production when SSL is properly configured
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)  # 0 = disabled, recommended: 31536000 (1 year)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)

# Content Security Policy (CSP) - Additional security headers
# Note: Django doesn't have built-in CSP, but you can use django-csp package
# For now, we'll configure basic security headers via middleware

# Additional Security Headers (handled by SecurityMiddleware)
# Prevent clickjacking attacks
X_FRAME_OPTIONS = 'DENY'  # Options: 'DENY', 'SAMEORIGIN', 'ALLOW-FROM'

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable XSS protection in browsers
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy - Controls how much referrer information is sent
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Options:
# - 'no-referrer': Never send referrer
# - 'same-origin': Only send referrer for same-origin requests
# - 'strict-origin-when-cross-origin': Send full referrer for same-origin, origin only for cross-origin HTTPS
# - 'origin-when-cross-origin': Send full referrer for same-origin, origin only for cross-origin

# Permissions Policy (formerly Feature Policy)
# Restrict browser features that can be used
PERMISSIONS_POLICY = {
    # List of features that are allowed to be used.
    # If the feature is not in the list, it will be blocked.
    # If the feature is in the list, it will be allowed to be used.

    'accelerometer': [], #Accelerometer is a sensor that measures the acceleration of the device.
    'ambient-light-sensor': [],
    'autoplay': [],
    'camera': [],
    'display-capture': [],
    'document-domain': [],
    'encrypted-media': [],
    'fullscreen': [],
    'geolocation': [],
    'gyroscope': [],
    'magnetometer': [],
    'microphone': [],
    'midi': [],
    'payment': [],
    'usb': [],
}

# ============================================================================
# DJANGO AXES CONFIGURATION (Brute Force Protection)
# ============================================================================
#
# Django Axes provides protection against brute force attacks by tracking
# failed login attempts and implementing lockout mechanisms.

# Enable Axes
AXES_ENABLED = env.bool('AXES_ENABLED', default=True)

# Number of failed login attempts before lockout
AXES_FAILURE_LIMIT = env.int('AXES_FAILURE_LIMIT', default=5)

# Time to wait (in hours) before allowing retry after lockout
AXES_COOLOFF_TIME = env.int('AXES_COOLOFF_TIME', default=1)  # 1 hour

# Lockout method: 'axes.lockout.database_lockout' uses database
# Other options: 'axes.lockout.cache_lockout', 'axes.lockout.memory_lockout'
AXES_LOCKOUT_CALLABLE = 'axes.lockout.database_lockout'

# Reset failed attempts on successful login
AXES_RESET_ON_SUCCESS = env.bool('AXES_RESET_ON_SUCCESS', default=True)

# Lockout parameters (what to track for lockout)
# Options: 'ip_address', 'username', 'user_agent', 'username_and_ip'
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']

# Enable Axes admin interface
AXES_ENABLE_ADMIN = env.bool('AXES_ENABLE_ADMIN', default=True)

# Verbose logging
AXES_VERBOSE = env.bool('AXES_VERBOSE', default=True)

# Logger name for Axes
AXES_LOGGER = 'axes.watch_login'

# Cache configuration (if using cache-based lockout)
AXES_CACHE = 'default'
AXES_CACHE_KEY_PREFIX = 'axes'

# IP whitelist (never lock these IPs)
AXES_IP_WHITELIST = env.list('AXES_IP_WHITELIST', default=[])

# IP blacklist (always lock these IPs)
AXES_IP_BLACKLIST = env.list('AXES_IP_BLACKLIST', default=[])

# Username whitelist (never lock these users)
AXES_USERNAME_WHITELIST = env.list('AXES_USERNAME_WHITELIST', default=[])

# Disable access log (set to False to enable detailed logging)
AXES_DISABLE_ACCESS_LOG = env.bool('AXES_DISABLE_ACCESS_LOG', default=False)

# ============================================================================
# RATE LIMITING CONFIGURATION
# ============================================================================
#
# Rate limiting is implemented using django-ratelimit decorator.
# Additional throttling is configured in REST_FRAMEWORK settings above.

# Cache backend for rate limiting (use Redis in production)
RATELIMIT_USE_CACHE = 'default'

# ============================================================================
# TOTP/MFA CONFIGURATION
# ============================================================================
#
# Time-based One-Time Password (TOTP) for Multi-Factor Authentication

# TOTP issuer name (shown in authenticator apps)
TOTP_ISSUER_NAME = env.str('TOTP_ISSUER_NAME', default='Secure E-Commerce')

# TOTP time step (in seconds, default 30 seconds)
TOTP_INTERVAL = env.int('TOTP_INTERVAL', default=30)

# TOTP digits (default 6)
TOTP_DIGITS = env.int('TOTP_DIGITS', default=6)

# TOTP window (number of time steps to allow for clock skew)
TOTP_WINDOW = env.int('TOTP_WINDOW', default=1)

# ============================================================================
# AUDIT LOGGING CONFIGURATION
# ============================================================================
#
# Audit logging is handled by AuditLoggingMiddleware.
# All security-relevant events are logged to the AuditLog model.

# Enable audit logging
AUDIT_LOGGING_ENABLED = env.bool('AUDIT_LOGGING_ENABLED', default=True)

# Log all requests (set to False to log only security events)
AUDIT_LOG_ALL_REQUESTS = env.bool('AUDIT_LOG_ALL_REQUESTS', default=False)

# ============================================================================
# CORS CONFIGURATION
# ============================================================================
#
# Cross-Origin Resource Sharing (CORS) configuration

# CORS allowed origins (from environment variable)
# Example: CORS_ALLOWED_ORIGINS = ['https://example.com', 'https://www.example.com']
# Already set above from environment
# Add Flutter web ports if not already included
if 'http://localhost:8080' not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append('http://localhost:8080')
if 'http://127.0.0.1:8080' not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append('http://127.0.0.1:8080')
# Allow any localhost port for development (Flutter web uses random ports)
# This is safer than CORS_ALLOW_ALL_ORIGINS=True as it only allows localhost
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
# Always allow localhost ports for development (Flutter web uses random ports)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

# CORS allowed methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# CORS preflight cache duration (in seconds)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# ============================================================================
# CACHING CONFIGURATION
# ============================================================================
#
# Cache configuration for rate limiting and performance

# Use Redis for caching in production
# For development, use local memory cache
if env.bool('USE_REDIS_CACHE', default=False):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': env.str('REDIS_URL', default='redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'secure_ecommerce',
            'TIMEOUT': 300,  # 5 minutes default timeout
        }
    }
else:
    # Local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
#
# Comprehensive logging configuration for security monitoring

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': env.str('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'axes': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)   