"""
Django settings for secure_ecommerce_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'products',
    'orders',
    'payments',
    'reviews',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", #CORS vulnerability prevention
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'secure_ecommerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'secure_ecommerce_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('DB_NAME'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': env.str('DB_HOST'),
        'PORT': env.str('DB_PORT'),
        'OPTIONS': {
            # Connection timeout in seconds which is the time to wait for a connection to be established.
            'connect_timeout': env.int('DB_CON_TIMEOUT'),
            # SSL mode which is the SSL mode to use for the connection.
            # SSL mode can be one of the following:
            # - 'disable': No SSL encryption.
            # - 'prefer': Prefer SSL encryption, but allow non-SSL connections.
            # - 'require': Require SSL encryption, and reject non-SSL connections.
            # - 'verify-ca': Verify the certificate against a trusted CA.
            # - 'verify-full': Verify the certificate against a trusted CA and the server's hostname.
            'sslmode': env.str('DB_SSLMODE'),
        },
        'CONN_MAX_AGE': env.int('DB_CON_MAX_AGE'),  # Connection max age in seconds which is the time to keep the connection alive.
    }
}

# ============================================================================
# AUTHENTICATION CONFIGURATION
# ============================================================================

AUTH_USER_MODEL = 'authentication.User'




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# DJANGO REST FRAMEWORK & JWT AUTHENTICATION
# ============================================================================
#
# API endpoints require JWT credentials by default. Public-facing views
# (registration, login, password reset) explicitly override this with
# `AllowAny` so they remain accessible without a token.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Align Simple JWT lifetimes with the security recommendations documented in
# `jwt_oauth_otp_configuration.txt`. Adjust via environment variables if an
# environment needs shorter or longer validity windows.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Brute-force safeguards used by the login serializer. Override these values
# in the environment to tune how many failed attempts are tolerated and how
# long an account remains locked after the threshold is exceeded.
AUTH_LOCKOUT_THRESHOLD = env.int('AUTH_LOCKOUT_THRESHOLD', default=5)
AUTH_LOCKOUT_MINUTES = env.int('AUTH_LOCKOUT_MINUTES', default=15)

# ============================================================================
# HTTPS/SSL SECURITY CONFIGURATION
# ============================================================================

# Force HTTPS in production
# Set to True when behind a proxy that handles SSL termination (e.g., nginx, load balancer)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Force all HTTP requests to redirect to HTTPS
# Set to True in production when SSL is properly configured
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)

# Ensure cookies are only sent over HTTPS
# Set to True in production
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)

# Ensure CSRF cookies are only sent over HTTPS
# Set to True in production
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)

# Prevent cookies from being accessed by JavaScript (XSS protection)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Set SameSite attribute for cookies to prevent CSRF attacks
# Options: 'Strict', 'Lax', 'None'
# 'Strict': Cookie is never sent in cross-site requests
# 'Lax': Cookie is sent in top-level navigation (default, good balance)
# 'None': Cookie is sent in all cross-site requests (requires Secure flag)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HTTP Strict Transport Security (HSTS)
# Forces browsers to only use HTTPS for a specified period
# Set to True in production when SSL is properly configured
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)  # 0 = disabled, recommended: 31536000 (1 year)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)

# Content Security Policy (CSP) - Additional security headers
# Note: Django doesn't have built-in CSP, but you can use django-csp package
# For now, we'll configure basic security headers via middleware

# Additional Security Headers (handled by SecurityMiddleware)
# Prevent clickjacking attacks
X_FRAME_OPTIONS = 'DENY'  # Options: 'DENY', 'SAMEORIGIN', 'ALLOW-FROM'

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable XSS protection in browsers
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy - Controls how much referrer information is sent
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Options:
# - 'no-referrer': Never send referrer
# - 'same-origin': Only send referrer for same-origin requests
# - 'strict-origin-when-cross-origin': Send full referrer for same-origin, origin only for cross-origin HTTPS
# - 'origin-when-cross-origin': Send full referrer for same-origin, origin only for cross-origin

# Permissions Policy (formerly Feature Policy)
# Restrict browser features that can be used
PERMISSIONS_POLICY = {
    # List of features that are allowed to be used.
    # If the feature is not in the list, it will be blocked.
    # If the feature is in the list, it will be allowed to be used.

    'accelerometer': [], #Accelerometer is a sensor that measures the acceleration of the device.
    'ambient-light-sensor': [],
    'autoplay': [],
    'camera': [],
    'display-capture': [],
    'document-domain': [],
    'encrypted-media': [],
    'fullscreen': [],
    'geolocation': [],
    'gyroscope': [],
    'magnetometer': [],
    'microphone': [],
    'midi': [],
    'payment': [],
    'usb': [],
}   