# Generated by Django 6.0 on 2025-12-04 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Product rating from 1 (worst) to 5 (best)', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5')])),
                ('title', models.CharField(help_text='Review title/summary', max_length=200)),
                ('comment', models.TextField(blank=True, help_text='Detailed review comment')),
                ('is_approved', models.BooleanField(default=False, help_text='If True, review is visible to customers. Requires moderation.')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='If True, customer has purchased this product')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of customers who found this review helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when review was last updated')),
                ('customer', models.ForeignKey(help_text='Customer who wrote this review', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved', 'rating'], name='reviews_rev_product_c82003_idx'), models.Index(fields=['customer', 'created_at'], name='reviews_rev_custome_13ae16_idx')],
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
