# Generated by Django 6.0 on 2025-12-04 17:11

import authentication.file_upload_models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique machine-friendly role identifier, e.g. ADMIN, SUPPORT_AGENT.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Role names must be uppercase letters and underscores only (3-32 chars).', regex='^[A-Z_]{3,32}$')])),
                ('display_name', models.CharField(help_text='Human readable role label shown in UIs.', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Context about what this role can do and when to grant it.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive roles remain for audit history but cannot be newly assigned.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(db_index=True, help_text='Unique challenge identifier', max_length=100, unique=True)),
                ('challenge', models.TextField(help_text='Challenge data (base64-encoded)')),
                ('challenge_type', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], help_text='Type of challenge', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Timestamp when challenge expires')),
                ('is_used', models.BooleanField(default=False, help_text='If True, challenge has been used and cannot be reused')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when challenge was created')),
            ],
            options={
                'verbose_name': 'WebAuthn Challenge',
                'verbose_name_plural': 'WebAuthn Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(db_index=True, help_text='Unique credential identifier from WebAuthn', max_length=255, unique=True)),
                ('public_key', models.TextField(help_text='Public key for signature verification (base64-encoded)')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Usage counter (incremented on each authentication)')),
                ('name', models.CharField(help_text="User-friendly name (e.g., 'iPhone Face ID', 'YubiKey')", max_length=100)),
                ('authenticator_type', models.CharField(choices=[('platform', 'Platform Authenticator (Face ID, Touch ID, Windows Hello)'), ('cross-platform', 'Cross-Platform (Hardware Security Key)')], default='platform', help_text='Type of authenticator used', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='If False, credential is revoked and cannot be used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when credential was registered')),
                ('last_used', models.DateTimeField(blank=True, help_text='Timestamp when credential was last used for authentication', null=True)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='If True, user has enabled Multi-Factor Authentication'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key for MFA (encrypted in production)', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='International E.164 format recommended, e.g. +21612345678.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in international format (8-15 digits, optional leading +).', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='3-50 characters. Letters, numbers, underscores, periods and hyphens allowed.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-50 characters and may include letters, numbers, underscores, periods or hyphens.', regex='^[A-Za-z0-9_.-]{3,50}$')]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Action type: LOGIN, LOGOUT, CREATE, UPDATE, DELETE, ACCESS_DENIED, etc.', max_length=100)),
                ('resource_type', models.CharField(db_index=True, help_text='Resource type: USER, PRODUCT, ORDER, PAYMENT, etc.', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource (if applicable)', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client making the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the HTTP request')),
                ('request_path', models.CharField(blank=True, help_text='URL path of the request', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method: GET, POST, PUT, DELETE, etc.', max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('BLOCKED', 'Blocked')], db_index=True, default='SUCCESS', help_text='Status of the action', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data in JSON format')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the event occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original filename (sanitized)', max_length=255)),
                ('stored_filename', models.CharField(help_text='Stored filename (UUID-based, secure)', max_length=255, unique=True)),
                ('file_path', models.FileField(help_text='File storage path', max_length=500, upload_to=authentication.file_upload_models.secure_file_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('product_image', 'Product Image'), ('avatar', 'Avatar'), ('other', 'Other')], default='other', help_text='Type of file', max_length=50)),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file content (for integrity verification)', max_length=64)),
                ('is_verified', models.BooleanField(default=False, help_text='If True, file has passed security checks')),
                ('is_quarantined', models.BooleanField(default=False, help_text='If True, file is quarantined pending security review')),
                ('virus_scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='pending', help_text='Virus scan status', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If True, file is publicly accessible')),
                ('description', models.TextField(blank=True, help_text='Optional file description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when file was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when file was last updated')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when file was verified', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Roles that can access this file', related_name='accessible_files', to='authentication.role')),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('verify', 'Verify'), ('quarantine', 'Quarantine'), ('release', 'Release from Quarantine')], help_text='Action performed', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked')], default='success', help_text='Status of the operation', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when action occurred')),
                ('file_upload', models.ForeignKey(help_text='File upload being logged', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='authentication.fileupload')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload Log',
                'verbose_name_plural': 'File Upload Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Administrator who granted this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_memberships', to='authentication.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User role assignment',
                'verbose_name_plural': 'User role assignments',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Collection of authorization roles granted to this account.', related_name='users', through='authentication.UserRole', through_fields=('user', 'role'), to='authentication.role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='authenticat_usernam_61ef80_idx'),
        ),
        migrations.AddField(
            model_name='webauthnchallenge',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User for registration challenges (null for authentication)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='user',
            field=models.ForeignKey(help_text='User who owns this credential', on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_3b88ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'status', 'timestamp'], name='authenticat_action_64372c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='authenticat_ip_addr_056073_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='authenticat_resourc_b40bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadlog',
            index=models.Index(fields=['file_upload', 'timestamp'], name='authenticat_file_up_c12e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadlog',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_554767_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadlog',
            index=models.Index(fields=['action', 'status'], name='authenticat_action_1078ef_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_hash'], name='authenticat_file_ha_5fa271_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='authenticat_uploade_523362_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_type', 'is_verified'], name='authenticat_file_ty_28fc96_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['virus_scan_status', 'is_quarantined'], name='authenticat_virus_s_6b4ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['challenge_id', 'is_used'], name='authenticat_challen_ab497e_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['user', 'challenge_type'], name='authenticat_user_id_d1c4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthnchallenge',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_cd80e6_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_3a7b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['credential_id'], name='authenticat_credent_b2eae4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webauthncredential',
            unique_together={('user', 'credential_id')},
        ),
    ]
