# Generated by Django 6.0 on 2025-12-04 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('critical', 'Critical')], db_index=True, default='healthy', help_text='Overall system health status', max_length=20)),
                ('api_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down')], default='operational', help_text='API status', max_length=20)),
                ('database_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down')], default='operational', help_text='Database status', max_length=20)),
                ('cache_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('down', 'Down')], default='operational', help_text='Cache status', max_length=20)),
                ('cpu_usage', models.FloatField(default=0, help_text='CPU usage percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('memory_usage', models.FloatField(default=0, help_text='Memory usage percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('disk_usage', models.FloatField(default=0, help_text='Disk usage percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_response_time', models.FloatField(default=0, help_text='Average response time in milliseconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('error_rate', models.FloatField(default=0, help_text='Error rate percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active_alerts_count', models.PositiveIntegerField(default=0, help_text='Number of active alerts')),
                ('critical_alerts_count', models.PositiveIntegerField(default=0, help_text='Number of critical alerts')),
                ('active_incidents_count', models.PositiveIntegerField(default=0, help_text='Number of active incidents')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional health data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when health snapshot was created')),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health Snapshots',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='AIAgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('scale_up', 'Scale Up Resources'), ('scale_down', 'Scale Down Resources'), ('restart_service', 'Restart Service'), ('clear_cache', 'Clear Cache'), ('block_ip', 'Block IP Address'), ('enable_maintenance', 'Enable Maintenance Mode'), ('disable_maintenance', 'Disable Maintenance Mode'), ('throttle_requests', 'Throttle Requests'), ('increase_timeout', 'Increase Timeout'), ('optimize_database', 'Optimize Database'), ('other', 'Other')], db_index=True, help_text='Type of action', max_length=50)),
                ('description', models.TextField(help_text='Action description')),
                ('triggered_by', models.CharField(help_text='What triggered this action (alert, metric, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], db_index=True, default='pending', help_text='Action status', max_length=20)),
                ('success', models.BooleanField(blank=True, help_text='Whether action was successful', null=True)),
                ('result_message', models.TextField(blank=True, help_text='Result message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when action was created')),
                ('executed_at', models.DateTimeField(blank=True, help_text='Timestamp when action was executed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when action was completed', null=True)),
            ],
            options={
                'verbose_name': 'AI Agent Action',
                'verbose_name_plural': 'AI Agent Actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'status'], name='monitoring__action__1fa904_idx'), models.Index(fields=['status', 'created_at'], name='monitoring__status_dcb97b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('system', 'System Alert'), ('performance', 'Performance Alert'), ('security', 'Security Alert'), ('database', 'Database Alert'), ('application', 'Application Alert')], db_index=True, help_text='Type of alert', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], db_index=True, default='warning', help_text='Alert severity', max_length=20)),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('message', models.TextField(help_text='Alert message')),
                ('source', models.CharField(help_text='Source of the alert (metric, event, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='active', help_text='Alert status', max_length=20)),
                ('ai_action_taken', models.BooleanField(default=False, help_text='If True, AI agent has taken action')),
                ('ai_action_description', models.TextField(blank=True, help_text='Description of AI agent action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional alert metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when alert was created')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Timestamp when alert was acknowledged', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when alert was resolved', null=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='monitoring__status_d7b628_idx'), models.Index(fields=['alert_type', 'created_at'], name='monitoring__alert_t_792ea6_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('disk', 'Disk Usage'), ('response_time', 'Response Time'), ('error_rate', 'Error Rate'), ('throughput', 'Throughput'), ('db_connections', 'Database Connections'), ('db_query_time', 'Database Query Time'), ('security_events', 'Security Events'), ('failed_logins', 'Failed Logins'), ('api_requests', 'API Requests')], db_index=True, help_text='Type of metric', max_length=50)),
                ('value', models.FloatField(help_text='Metric value', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='percent', help_text='Unit of measurement (percent, ms, count, etc.)', max_length=20)),
                ('warning_threshold', models.FloatField(blank=True, help_text='Warning threshold value', null=True)),
                ('critical_threshold', models.FloatField(blank=True, help_text='Critical threshold value', null=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], db_index=True, default='healthy', help_text='Current status based on thresholds', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metric metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when metric was recorded')),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='monitoring__metric__7fdceb_idx'), models.Index(fields=['status', 'timestamp'], name='monitoring__status_3330f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Incident title', max_length=200)),
                ('description', models.TextField(help_text='Incident description')),
                ('incident_type', models.CharField(choices=[('outage', 'Outage'), ('performance', 'Performance Degradation'), ('security', 'Security Breach'), ('data_loss', 'Data Loss'), ('other', 'Other')], db_index=True, help_text='Type of incident', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Incident severity', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', help_text='Incident status', max_length=20)),
                ('ai_detected', models.BooleanField(default=False, help_text='If True, incident was detected by AI agent')),
                ('ai_resolved', models.BooleanField(default=False, help_text='If True, incident was resolved by AI agent')),
                ('ai_actions', models.JSONField(blank=True, default=list, help_text='List of AI agent actions taken')),
                ('resolution', models.TextField(blank=True, help_text='Incident resolution description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional incident metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when incident was created')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when incident was resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when incident was closed', null=True)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='monitoring__status_40b570_idx'), models.Index(fields=['incident_type', 'created_at'], name='monitoring__inciden_e4a193_idx')],
            },
        ),
    ]
