# Generated by Django 6.0 on 2025-12-04 17:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Product name (max 200 characters)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - unique product identifier', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in the base currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity available', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='If False, product is hidden from customers but preserved for audit')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products appear prominently in listings')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when product was last updated')),
                ('seller', models.ForeignKey(help_text='User who created/owns this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'), models.Index(fields=['seller', 'created_at'], name='products_pr_seller__c7d447_idx')],
            },
        ),
    ]
